name: publish to nuget
on:
  push:
    branches:
      - master
jobs:
  publish:
    name: build, pack & publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # - name: Setup dotnet
      #   uses: actions/setup-dotnet@v1
      #   with:
      #     dotnet-version: 3.1.200

      # Publish
      # https://github.com/brandedoutcast/publish-nuget
      - name: publish on version change
        id: publish_nuget
        uses: brandedoutcast/publish-nuget@v2
        with:
          PROJECT_FILE_PATH: ClockworkFramework.Core/ClockworkFramework.Core.csproj
          BUILD_CONFIGURATION: Release
          VERSION_REGEX: ^\s*<Version>(.*)<\/Version>\s*$
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
